ALIGNMENT_REFERENCE:
  "NC_045512.2"
PROBLEMATIC_VCF:
  "https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/da322c32004f7b16bdaa6a8ee7fd24d56e79d9dc/problematic_sites_sarsCov2.vcf"
FEATURES_JSON:
  "config/sarscov2_features.json"
COORDINATES_JSON:
  "config/sarscov2_coordinates.json"
GENETIC_CODE_JSON:
  "config/standard_genetic_code.json"
TREE_MODEL:
  "GTR+F+I+G4"
UFBOOT_REPS:
  1000
SHALRT_REPS:
  1000
VC:
  MAX_DEPTH: 0
  MIN_QUALITY: 0
  IVAR_QUALITY: 20
  IVAR_FREQ: 0.05
  IVAR_DEPTH: 30
ANNOTATION:
  SNPEFF_COLS:
    CHROM: CHROM
    POS: POS
    REF: REF
    ALT: ALT
    EFFECT: "ANN[*].EFFECT"
    IMPACT: "ANN[*].IMPACT"
    BIOTYPE: "ANN[*].BIOTYPE"
    GENE: "ANN[*].GENE"
    GENEID: "ANN[*].GENEID"
    FEATURE: "ANN[*].FEATURE"
    FEATUREID: "ANN[*].FEATUREID"
    HGVS_P: "ANN[*].HGVS_P"
    HGVS_C: "ANN[*].HGVS_C"
  FILTER_INCLUDE:  # see: https://pcingola.github.io/SnpEff/adds/VCFannotationformat_v1.0.pdf
  #  IMPACT: [HIGH, MODERATE, LOW]
  FILTER_EXCLUDE:
    EFFECT: [upstream_gene_variant, downstream_gene_variant]
  VARIANT_NAME_PATTERN: "{GENE}:{coalesce(HGVS_P, HGVS_C)}"  # dplyr's coalesce finds the first non-missing element
DEMIX:
  PATHOGEN: "SARS-CoV-2"
  MIN_QUALITY: 20
  COV_CUTOFF: 30
  MIN_ABUNDANCE: 0.0001
  CONFIRMED_ONLY: false
  DEPTH_CUTOFF: 0
  RELAXED_MRCA: false
  RELAXED_MRCA_THRESH: 0.9
  AUTO_ADAPT: false
  SOLVER: "CLARABEL"
WINDOW:
  WIDTH: 1000
  STEP: 50
GISAID:
  CREDENTIALS: "config/gisaid.yaml"
  DATE_COLUMN: "CollectionDate"
  LOCATION_COLUMN: "ResidenceCity"
  ACCESSION_COLUMN: "GISAIDEPI"
DIVERSITY_REPS:
  1000
USE_BIONJ: false
COR:
  METHOD: "pearson"
  EXACT: null
LOG_PY_FMT:
  "%(asctime)s - %(name)s - %(levelname)-8s - %(message)s"
PLOTS:
  "config/design_plots.R"
PLOT_GENOME_REGIONS:
  "config/nsp_annotation.csv"
REPORT_QMD:
  "template.qmd"
