ALIGNMENT_REFERENCE:
  "NC_045512.2"
PROBLEMATIC_VCF:
  "https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/da322c32004f7b16bdaa6a8ee7fd24d56e79d9dc/problematic_sites_sarsCov2.vcf"
FEATURES_JSON:
  "config/sarscov2_features.json"
GENETIC_CODE_JSON:
  "config/standard_genetic_code.json"
TREE_MODEL:
  "GTR+F+I+G4"
UFBOOT_REPS:
  1000
SHALRT_REPS:
  1000
VC:
  MAX_DEPTH: 0
  MIN_QUALITY: 0
  IVAR_QUALITY: 20
  IVAR_FREQ: 0.05
  IVAR_DEPTH: 30
DEMIX:
  PATHOGEN: "SARS-CoV-2"
  MIN_QUALITY: 20
  COV_CUTOFF: 30
  MIN_ABUNDANCE: 0.0001
  CONFIRMED_ONLY: false
  DEPTH_CUTOFF: 30
  RELAXED_MRCA: false
  RELAXED_MRCA_THRESH: 0.9
  AUTO_ADAPT: false
WINDOW:
  WIDTH: 1000
  STEP: 50
GISAID:
  CREDENTIALS: "config/gisaid.yaml"
  DATE_COLUMN: "CollectionDate"
  LOCATION_COLUMN: "ResidenceCity"
  ACCESSION_COLUMN: "GISAIDEPI"
DIVERSITY_REPS:
  1000
USE_BIONJ: false
COR:
  METHOD: "pearson"
  EXACT: null
LOG_PY_FMT:
  "%(asctime)s - %(name)s - %(levelname)-8s - %(message)s"
PLOTS:
  "config/design_plots.R"
PLOT_GENOME_REGIONS:
  "config/nsp_annotation.csv"
REPORT_QMD:
  "template.qmd"
